name: project-name
version: 0.0.1.0
author: Marco Yuen
language: GHC2021

dependencies:
  - base >= 4.18 && < 5
  - bytestring
  - containers
  - exceptions
  - extra
  - mtl
  - text
  - transformers

ghc-options:
  - -Wcompat
  - -Wincomplete-patterns
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -Wunused-packages
  - -fdefer-typed-holes
  - -fshow-hole-constraints
  - -fwrite-ide-info
  - -fprint-explicit-foralls

default-extensions:
  - DataKinds
  - GADTs
  - LambdaCase
  - NamedWildCards
  - OverloadedRecordDot
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - ViewPatterns

# library:
#   source-dirs: src

# executables:
#   exe:
#     main: Main.hs
#     source-dirs: app
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N
#     dependencies:
#       - package-name

tests:
  test:
    main: Driver.hs
    source-dirs: test
    build-tools:
      - tasty-discover:tasty-discover
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-hspec
