name:       project-name
version:    0.0.1.0
copyright:  © 2025 Marco Yuen
author:     Marco Yuen
license:    GPL-3.0-or-later
language:   GHC2021
synopsis:   Project template

# data-files:
#   - data/*.*

dependencies:
  - base >= 4.18 && < 5
  # - aeson
  - bytestring
  - exceptions
  - extra
  - generic-lens
  - lens
  # - lens-aeson
  - monad-logger
  - mtl
  # - singletons
  # - singletons-th
  - string-interpolate
  - text
  - text-show
  - transformers
  - yaml

ghc-options:
  - -Wcompat
  - -Wincomplete-patterns
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -Wunused-packages
  - -fdefer-typed-holes
  - -fshow-hole-constraints
  - -fwrite-ide-info
  - -fprint-explicit-foralls

default-extensions:
  - DataKinds
  - DerivingStrategies
  - DuplicateRecordFields
  - GADTs
  - LambdaCase
  - MultilineStrings
  - NamedWildCards
  - OverloadedLabels
  - OverloadedLists
  - OverloadedRecordDot
  - OverloadedRecordUpdate
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - RecordWildCards
  - TypeAbstractions
  - ViewPatterns
  - NoFieldSelectors
  - NoStarIsType

# library:
#   source-dirs: src

# internal-libraries:
#   lib1:
#     source-dirs: lib1/src

# executables:
#   exe:
#     main: Main.hs
#     source-dirs: app
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N
#     dependencies:
#       - package-name

tests:
  project-test:
    main: Driver.hs
    source-dirs: test
    build-tools:
      - tasty-discover:tasty-discover
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-hspec
